version: '3.8'

services:
  backend:
    build: .
    container_name: rag_backend_api
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: rag_nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend